<li><a href="do.CreateRecReq">Create Recruitment Request</a></li>
<li><a href="do.RRwork">V.E.D Recruitment Request</a></li>
<li><a href="do.CreatePC">Create Placement Consultant</a></li>
<li><a href="do.EditPC">V.E.D.S. Placement Consultant</a></li>
<li><a href='VacancyIdList'>Display Candidate Profiles</a></li>
<li><a href='EmployeeIdListTA'>Appoint Test Admin</a></li>
<li><a href='EmployeeIdListTA'>Appoint Test Admin</a></li>
<li><a href='DisplayDeleteTA'>Display Test Admin</a></li>
<li><a href='creat_test.jsp'>Create Test Schedule</a></li>
<li><a href='DisplayTests'>Display Test Schedule</a></li>
<li><a href='DisplayEditDeleteCandStatus'>Candidate Status</a></li>
<li><a href="BGCServlet">Select BGC Admin</a></li>
<li><a href="viewbgc_admin_servlet">View BGC Admin</a></li>
<li><a href="Schedule_BGC_servlet">Schedule BGC Test</a></li>
<li><a href="displayDate">View BGC Schedule</a></li>
<li><a href="emp_dropdown_servlet">Add Employee</a></li>
<li><a href="Search_emp.jsp">View Employee Details</a></li>
<li><a href="editctc_servlet">Edit CTC and Designation</a></li>